import{i as l,S as u}from"./assets/vendor-46aac873.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const p="/goit-js-hw-11/assets/bi_x-octagon-378f247e.svg",i=document.querySelector(".js-search-form"),c=document.querySelector(".gallery");i.addEventListener("submit",d);function d(r){r.preventDefault(),i.insertAdjacentHTML("afterend",'<span class="loader"></span>');const e=r.target.elements.search.value;e!==""&&m(e).then(n=>{g(n.hits)}).then(n=>{document.querySelector(".loader").remove()}),i.reset()}function m(r){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"42121827-736028e2edd071afefc989558",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(n).then(s=>{if(!s.ok)throw new Error(`HTTP error! Status: ${s.status}`);return s.json()}).catch(s=>{throw console.error("Error fetching pictures:",s),s})}function f(r){return r.map(e=>`<li class="card-container">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image"></a>
    
    <div class="picture-card">
        <p><span class="description">Likes</span>${e.likes}</p>
        <p><span class="description">Views</span>${e.views}</p>
        <p><span class="description">Comments</span>${e.comments}</p>
        <p><span class="description">Downloads</span>${e.downloads}</p>
    </div>
</li>`).join("")}function g(r){if(c.innerHTML="",r.length===0)return l.show({title:"Error",titleColor:"rgba(255, 255, 255, 1)",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"rgba(255, 255, 255, 1)",backgroundColor:"rgba(239, 64, 64, 1)",iconUrl:p,position:"topRight"});const e=f(r);c.insertAdjacentHTML("beforeend",e),h()}function h(){let r=new u(".gallery a",{captionsData:"alt",captionDelay:250});r.on("show.simplelightbox"),r.refresh()}
//# sourceMappingURL=commonHelpers.js.map
