import{i as l,S as u}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const d="/goit-js-hw-11/assets/bi_x-octagon-378f247e.svg",i=document.querySelector(".js-search-form"),c=document.querySelector(".gallery");i.addEventListener("submit",p);function p(o){o.preventDefault();const t=o.target.elements.search.value,n=document.querySelector(".loader");t!==""&&!n&&(c.innerHTML="",i.insertAdjacentHTML("afterend",'<span class="loader"></span>'),m(t).then(r=>{setTimeout(()=>{const e=document.querySelector(".loader");e&&e.remove(),f(r.hits)},500)})),i.reset()}function m(o){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"42121827-736028e2edd071afefc989558",q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:100})}`;return fetch(n).then(r=>{if(!r.ok)throw new Error(`HTTP error! Status: ${r.status}`);return r.json()}).catch(r=>{throw r})}function f(o){if(o.length===0)return l.show({message:"Sorry, there are no images matching<br>your search query. Please try again!",messageColor:"rgba(255, 255, 255, 1)",backgroundColor:"rgba(239, 64, 64, 1)",iconUrl:d,position:"topRight"});const t=g(o);c.insertAdjacentHTML("beforeend",t),h()}function g(o){return o.map(t=>`<li class="gallery-item">
            <div class="image-container">
                <a href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image"></a>
            </div>
            <div class="gallery-card">
                <p><span class="description">Likes</span>${t.likes}</p>
                <p><span class="description">Views</span>${t.views}</p>
                <p><span class="description">Comments</span>${t.comments}</p>
                <p><span class="description">Downloads</span>${t.downloads}</p>
            </div>
        </li>`).join("")}function h(){let o=new u(".gallery a",{captionsData:"alt",captionDelay:250});o.on("show.simplelightbox"),o.refresh()}
//# sourceMappingURL=commonHelpers.js.map
